---
title: "1/3_Class"
author: "PoMingChen"
date: "2019/1/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
studentData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/studentFeatures.csv");
library(dplyr); library(stringr); library(lubridate); library(purrr); library(ggplot2); library(plotly)
```

```{r}
studentData
```

```{r}
.x<- "92a7Q7fee"  # readline(prompt="學號")
studentData %>%
  filter(學號==.x) -> student_i
library(magrittr) # 為了使用 %T>%
# student_i %>% 
#   select(學年, 學期, 學期PR) %T>% View -> studentPR
student_i %>%
  select(學年, 學期, 學期借書量) %T>% View -> studentLibrary
student_i %>%
  select(學系,學屆, 學年, 學期, 學期平均, 學期PR) %>%
  mutate(
    學年學期=as.factor(paste0(學年,"-",學期)),
    學期平均=round(學期平均,digits = 2)
    ) %T>% View -> studentGPA
```

```{r}
studentData %>%
  group_by(學系, 學屆, 學年, 學期) %>%
  summarise(
    同學平均成績=round(mean(學期平均),digits=2),
    同學中位成績=round(median(學期平均),digits=2),
    同學中位借書量=median(學期借書量)
  ) %>%
  ungroup %>%
  mutate(
    學年學期=as.factor(paste0(學年,"-",學期))
        )  -> studentSummary

studentSummary
```

```{r}
install.packages("DT")
```

```{r}
library(DT)
studentGPA %>%
  select(
    學年,學期,學期平均,學期PR
  ) %>%
DT::datatable(options = list(
  bPaginate = FALSE
)) -> gpaTable; gpaTable
```

```{r}
studentSummary %>% 
  filter(
    學系==studentGPA$學系[1],
    學屆==studentGPA$學屆[1]) -> classmateData
```

```{r}
#validClassmateData 取出有效的學期。

validClassmateData <-
  classmateData %>%
      filter((學年-學屆)*2+學期<=8)
validClassmateData$同學平均成績[nrow(validClassmateData)]-> yloc
validClassmateData$學年學期 %>% length -> xloc
studentGPA %>%
  ggplot()+
  geom_line(aes(x=學年學期,y=學期平均,group=1),size=1.5)+
  geom_line(
    data=validClassmateData,
    aes(x=學年學期,y=同學平均成績,group=1),
    color="#33B5FF",size=1.2,alpha=0.5)+
  annotate("text",x=c(xloc),y=yloc*0.996,label="同學平均",color="#2B95D2") +
  labs(x=NULL,y="學期平均")->
  studentGPAgg; studentGPAgg
```

```{r}
studentGPA %>%
  ggplot()+
  geom_line(aes(x=學年學期,y=學期PR,group=1),size=1.5)+
  labs(x=NULL,y="學期PR") -> studentPRgg
ggplotly(studentPRgg) -> studentPRggplotly
studentPRggplotly
```

```{r}
download.file("https://raw.githubusercontent.com/tpemartin/github-data/master/shinyExample.Rmd",destfile = "./shinyExample.Rmd")
```

