---
title: "1004_Class"
author: "PoMingChen"
date: "2018/10/4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
bopData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=10823&md5_url=e09fd24fad95da6d6cd67b2d05d3e878")
```

```{r}
library(dplyr)
bopData %>%
  rename(年季=`0`) -> bopData
```

```{r}
bopData %>%
  select(
    年季,
    `A.  經常帳`, 
    `B.  資本帳 1`,
    `C.  金融帳 1`,
    `D.  誤差與遺漏淨額`,
    `E.  準備與相關項目`) -> partialBop
```

```{r}
library(lubridate)
partialBop$年季 %>% yq() ->
  partialBop$年季
```

```{r}
partialBop
```

```{r}
partialBop %>% ggplot(aes(x=年季,y=`A.  經常帳`)) + geom_line() 
```

```{r}
partialBop %>% ggplot(aes(x=年季)) + 
  geom_line(aes(y=`A.  經常帳`)) + 
  geom_line(aes(y=`C.  金融帳 1`), linetype = "33")
```

#### 用gather轉換資料形式，會比較可以讓x y 軸的局部sample設定較方便。
```{r}
library(tidyr)
partialBop
partialBop %>% gather(項目,值,-年季) -> partialBopNew
#-年季，來先忽略他，但是這邊是需要寫在最後面的
partialBopNew
```

```{r}
partialBopNew %>% filter(項目=="A.  經常帳") -> CAdata
partialBopNew %>% filter(項目=="C.  金融帳 1") -> FAdata
CAdata %>% ggplot(aes(x=年季, y=值)) + geom_line() -> CAfig
```

```{r}
CAfig + geom_line(data = FAdata, linetype = "longdash")
```

```{r}
partialBopNew %>% ggplot(aes(x=年季, y=值)) + 
  geom_line(aes(color = 項目, linetype = 項目))
```

```{r}
partialBopNew
```

### scale
```{r}
library(ggplot2)
library(dplyr)
library(showtext)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE)
theme_set(theme_classic())
```

```{r}
mpg %>% ggplot(aes(x=cty,y=hwy,color=class))+
  geom_point()
```

```{r}
mpg %>% ggplot(aes(x=cty,y=hwy,color=class))+
  geom_point() -> f1

f1 + scale_color_manual(values=c("red","blue","green","tomato","tomato","#e86b97","blue"))
```

### scale_brewer(主要是配間斷變數，連續變數主要是配distiller)(手動改法，是discrete，continuous)(brewer，distiller)
```{r}
f1 + scale_color_brewer(type = "qual")

# sequential（強調順序）（遞增嚴重感）seq
# diverging （強調離異）(對立感) div
# 前面兩者會比較需要資料本身是有比較意義的。
# and qualitative（強調不同屬性）qual

#distiller: 利用brewer再去連續平滑色度變化
```

