---
title: "R Notebook"
output: html_notebook
---

### 5.2 連續變數

> scale_color_


#### gradient 範例
```{r}
library(ggplot2)
df <- data.frame(
  x = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = abs(rnorm(100))
)

# Default colour scale colours from light blue to dark blue
ggplot(df, aes(x, y)) +
  geom_point(aes(colour = z2)) -> gradientBase
gradientBase
```

#### sequential
```{r}
gradientBase+scale_color_gradient(low="#66FFFF",high="#6600FF")
```

#### diverging
```{r}
gradientBase+scale_colour_gradient2(midpoint = 1.5)
```

```{r}
library(scales)
show_col(c("red", "blue", muted("red"), muted("blue")))
```

```{r}
show_col(c("#704a6c","#f58220"))
```

### distiller
> 沒什麼想法，間斷就是用brewer，連續用distiller

#### sequential
```{r}
gradientBase+scale_color_distiller()
```

#### diverging
```{r}
#div是diverging的意思
gradientBase+scale_color_distiller(type="div", palette = "PRGn")
```

```{r}
library(readr)
InterestRateData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/InterestRateData.csv")

# 取出變數
InterestRateData %>% select(
  銀行,
  年月,
  `定存利率-三個月-固定`,
  `定存利率-一年期-固定`
) -> allBankData

# 修正class
allBankData %>% 
  mutate_at(vars(-銀行,-年月),funs(as.numeric(.))) ->
  allBankData

# 修正年月
library(stringr)
library(lubridate)
allBankData$年月 %>%
  str_c("1",.,"/01") %>%
  ymd()+years(911) -> allBankData$年月

# 移除多餘的row
allBankData %>% filter(!is.na(年月)) -> allBankData

# 產生利差
allBankData %>% mutate(利差=`定存利率-一年期-固定`-`定存利率-三個月-固定`) -> allBankData

# 產生平均利率及平均利差
allBankData %>% 
  select(年月,`定存利率-三個月-固定`,利差) %>%
  group_by(年月) %>%
  summarise(
    平均利率=mean(`定存利率-三個月-固定`,na.rm=T),
    平均利差=mean(利差,na.rm = T)) -> averageBankData

averageBankData
```

### 5.4 現場練習

### 畫出6家銀行的三個月定存利率走勢圖

```{r}
allBankData %>% filter(銀行 %in% "第一銀行") %>% ggplot(aes(x=`年月`,y=`定存利率-三個月-固定`)) + geom_line(aes(color=銀行), linetype = "33")
```


### 畫出平均利率走勢圖
```{r}
averageBankData %>% ggplot(aes(x=年月, y=平均利率)) + geom_line()
```

### 畫出利差以及利率走勢(alpha/distiller)
```{r}
averageBankData %>% ggplot(aes(x=年月, y=平均利率)) + geom_line() + geom_point(aes(alpha=平均利差), color="red") 
``` 

```{r}
averageBankData %>% ggplot(aes(x=年月, y=平均利率)) + geom_line() + geom_point(aes(color=平均利差)) + scale_color_distiller(type = "div")
```
