---
title: "0920_Class"
output: html_notebook
---

```{r}
library(readr)
```

```{r}
InterestRateData <- A13Rate
InterestRateData
```

#### 經濟討論

銀行掛牌利率為年利率。

月固定利率4.3，存100元，一個月後會拿到100*4.3%/12。

重點是在比較短期、長期的利率結構狀況，可以說出人民對於當下、短期未來、長期未來的預期狀況。


```{r}
library(dplyr)
subsetData <- InterestRateData %>%
  select(銀行,
           年月,
           `定存利率-一個月-固定`,
           `定存利率-二年期-固定`,
           `定存利率-三年期-固定`)
#`定存利率-一個月-固定`，要有``，才會表達成減號運算。
```

```{r}
subsetData
subsetDataTWbank <- subsetData %>%
  filter(銀行=="臺灣銀行")
```

Time: frequency and span (針對時間，需要特別跟電腦parse，詮釋，不可以用字串)
```{r}
library(dplyr)

#我打算再加一個變數。
#seq(起於,迄於...) 是一個萬用數列產生器，那用as.Date來表達（日期）的特質。
#變數類型為date
subsetDataTWbank$西元年月<-seq(as.Date("2001/01/01"),as.Date("2018/08/01"),"months") 
#季，quarters
```

```{r}
subsetDataTWbank[,c(3,4,5)] %>% 
  mutate_all(as.numeric) -> 
  subsetDataTWbank[,c(3,4,5)]
```

> 研究一下write csv這個可以幹嗎? 存檔

```{r}
write.csv(subsetDataTWbank, file="./subsetDataTWbank.csv")
```

#### 進入繪圖

```{r}
read.csv("./subsetDataTWbank.csv")
```

```{r}
library(ggplot2)
subsetDataTWbank %>% ggplot(aes(x=西元年月,y=`定存利率-一個月-固定`)) +
  geom_line()
```

```{r}
library(showtext)
font_files() #找到你的電腦有什麼字體。
```

```{r}
font_add("QYuan","Arial.ttf") # 新增字體

#This function registers new font families that can be used by package showtext and the SWF device in package R2SWF. Currently supported formats include but not limited to TrueType fonts(*.ttf, *.ttc) and OpenType fonts(*.otf).

showtext_auto(enable=TRUE) #啟用字體
```

```{r}
#最終層疊
subsetDataTWbank %>% ggplot(aes(x=西元年月,y=`定存利率-一個月-固定`))+
  geom_line()+
  theme(text=element_text(size=10,  family="QYuan"))+
  theme_classic()+
  labs(x="西元年月",y="利率：%")
```

### 寫作業

> 查詢如何直接drop特定一行
> 查詢如何為何會有X X1_1的產生
> mac投影解析度設定

```{r 引入資料}
read.csv("./hw/bop_aq.csv") -> HW1data
HW1data
```

```{r}
HW1data %>% select(c(1,2)) -> HW1dataSheet
HW1dataSheet %>% mutate(季資料 = HW1dataSheet$X) -> HW1dataSheet

HW1dataSheet %>% select(季資料,A...經常帳,everything()) -> HW1dataSheet
#經常帳總額。
#subsetDataTWbank$西元年月<-seq(as.Date("2001/01/01"),as.Date("2018/08/01"),"months") 

HW1dataSheet
HW1dataSheet$季資料 <- seq(as.Date("2014/07/01"),as.Date("2018/04/01"),"quarters")

HW1dataSheet[-c(3)]->HW1dataSheet
HW1dataSheet

```

```{r}
library(dplyr)
HW1dataSheet %>% ggplot(aes(x=季資料,y=A...經常帳)) +       geom_line()+
  theme(text=element_text(size=10,  family="QYuan"))+
  theme_classic()+
  labs(x="西元年月",y="經常帳：百萬美元") 
```

